title: Mike Nelson E-Portfolio # your name (or website title) here
logo: "/images/fullnelson.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/mike-nelson-problem-solver/">View My LinkedIn Profile</a> 
  <br>
  <a href="mailto:estimatingnorthwest@gmail.com">Email Me</a>
  <br>
  Mobile Phone: 406-540-2828
  <br><br>
theme: jekyll-theme-minimal
